package Engine;

public enum AttackType {
    DIAGONAL_LEFT,
    DIAGONAL_RIGHT,
    ROW,
    COLUMN,
    COLUMN_UP,
    COLUMN_DOWN,
    ROW_LEFT,
    ROW_RIGHT,
    DIAGONAL_LEFT_LEFT,
    DIAGONAL_LEFT_RIGHT,
    DIAGONAL_RIGHT_LEFT,
    DIAGONAL_RIGHT_RIGHT;
}
